export const CHANGE_PASSWORD = "settings/CHANGE_PASSWORD";
export const CHANGE_EMAIL = "settings/SET_MANAGER_SETTINGS";
export const CONNECTED_STRIPE = "settings/CONNECTED_STRIPE";

export const SET_PAYMENTS_SETTING = "settings/SET_PAYMENTS_SETTING";
export const SET_SETTINGS_FETCHING = "settings/SET_SETTINGS_FETCHING";
export const SET_DELIVERECT_SETTINGS = "settings/SET_DELIVERECT_SETTINGS";
export const SET_MAIN_SERVICE_CHARGE = "settings/SET_MAIN_SERVICE_CHARGE";
export const SET_PICK_UP_SERVICE_CHARGE = "settings/SET_PICK_UP_SERVICE_CHARGE";
export const SET_STRIPE_STATUS = "settings/SET_RESTAURANT_STRIPE_STATUS";
